api:
  version: '1'
  prefix: '/api'
formatters:
  - type: 'application/json'
    class: 'JSONFormatter'
    response:
      type: 'application/json'
      service: 's3'
  - type: 'application/pdf'
    class: 'PDFFormatter'
    response:
      type: 'application/json'
      service: 'http'
  - type: 'application/xml'
    class: 'XMLFormatter'
    response:
      type: 'application/xml'
      service: 'http'

storage:
  type: 's3'
  url: 'http://localhost:8000'
